config/routes.rb
Rails.application.routes.draw do
    devise_for :users do
	  resources :events
	end



resources :events
  root 'events#index'
  get 'tags/:tag', to: 'events#index', as: :tag
  get :join, to: 'events#join', as: 'join'
  get  :accept_request, to: 'events#accept_request', as: 'accept_request'
  get  :reject_request, to: 'events#reject_request', as: 'reject_request'
  get  :my_events, to: 'events#my_events', as: 'my_events'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :user
	belongs_to :event

	include Workflow
	workflow_column :state

	workflow do 
		state :request_sent do
			event :accept, :transitions_to => :accepted
			event :reject, :transitions_to => :rejected
		end
		state :accepted
		state :rejected
	end

	def self.show_accepted_attendees(event_id)
		Attendance.where(event_id: event_id, state: :accepted)
	end


	def self.join_event(user_id, event_id, state)
		self.create(user_id: user_id, event_id: event_id, state: state)
	end
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :organizer, class_name: 'User'
	has_many :attendances
	has_many :users, through: :attendances
    
    has_many :taggings
	has_many :tags, through: :taggings
	
	extend FriendlyId
	friendly_id :title, use: [:slugged, :finders]

	

	def self.show_accepted_attendees(event_id)
		Attendance.where(event_id: event_id, state: :accepted)
	end

	def self.pending_requests(event_id)
		Attendance.where(event_id: event_id, state: 'request_sent')
	end

	def all_tags=(names)
		self.tags = names.split(",").map do |t|
			Tag.where(name: t.strip).first_or_create
		end
	end

	def all_tags
		tags.map(&:name).join(", ")
	end

	def self.tagged_with(name)
       Tag.find_by_name!(name).events
     end

    def self.tag_counts
    	Tag.select("tags.name, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
    end

    def self.event_owner(organizer_id)
    	User.find_by id: organizer_id
    end
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :events, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :organized_events, class_name: "Event", foreign_key: "organizer_id"
  has_many :attendances
  has_many :events, through: :attendances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :event_owner!, only: [:edit,:update,:destroy]
  respond_to :html, :xml, :json


  def my_events
    @events = current_user.organized_events
  end

  def accept_request
    @event = Event.friendly_id.find_by(params[:id])
    @attendance = Attendance.find_by(id: params[:attendance_id]) rescue nil
    @attendance.state = 'accepted'
    "Applicant Accepted" if @attendance.save
    #render json: (@attendance)
    redirect_to @event
  end

  def reject_request
    @event = Event.friendly_id.find_by(params[:id])
    @attendance = Attendance.find_by(id: params[:attendance_id]) rescue nil
    @attendance.state = 'rejected'
    "Applicant rejected" if @attendance.save
    #render json: (@attendance)
    redirect_to @event
  end

  # GET /events
  # GET /events.json
  def index
    if params[:tag]
      @events = Event.tagged_with(params[:tag])
    else
      @events = Event.all
    end
  end

  def join
    @event = Event.friendly_id.find_by(params[:id])
    @attendance = Attendance.join_event(current_user.id, params[:event_id], 'request_sent')
    flash[:notice] = 'Request Sent' if @attendance.save

    #render json: (@attendance)
    redirect_to @event
  end

  # GET /events/1
  # GET /events/1.json
  def show

    @event_owners = @event.organizer
    @pending_requests = Event.pending_requests(@event.id) 
    @attendees = Event.show_accepted_attendees(@event.id)
  end

  # GET /events/new
  def new
    @event = current_user.organized_events.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = current_user.organized_events.create(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.friendly_id.find(params[:id])
    end

    def event_owner!
      authenticate_user!
        if @event.organizer_id != current_user.id
          redirect_to events_path
          flash[:notice] = 'You do not have enough permissions to do this'
        end
    end  

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :start_date, :end_date, :location, :agenda, :address, :organizer_id, :all_tags)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def tag_cloud(tags, classes)
		max = tags.sort_by(&:count).last
		tags.each do |tag|
			index = tag.count.to_f / max.count * ( classes.size - 1)
			yield(tag, classes[index.round])
		end
	end

	def avatar_url(user)
		gravatar_id = Digest::MD5::hexdigest(user.email).downcase
		"https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identicon&s=150"
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div><br>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.text_field :start_date, placeholder: "Date and Time", class: 'form-control', id: 'flatpickr-input' %>
  </div><br>


  <div class="field">
    <%= form.label :end_date %>
    <%= form.text_field :end_date, placeholder: "Date and Time", class: 'form-control', id: 'flatpickr-input'   %>
  </div><br>
  <script type="text/javascript">
    $(document).ready(function(){

      flatpickr('#flatpickr-input', {
      enableTime: true,
      dateFormat: "Y-m-d H:i",
    })
      
    });
  </script><br><br>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, class: 'form-control'  %>
  </div><br>

  <div class="field">
    <%= form.label :agenda %>
    <%= form.text_area :agenda, class: 'form-control'  %>
  </div><br>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, class: 'form-control'  %>
  </div><br>

  <div class="hidden field">
    <%= form.label :organizer_id %>
    <%= form.number_field :organizer_id, value: current_user.id %>
  </div><br>

  <div class="field">
    <%= form.label :all_tags, "List All Tags, separate each tag by a comma " %>
    <%= form.text_field :all_tags, class: 'form-control'  %>
  </div><br>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary'  %>
  </div>
<% end %>

app/views/events/_tag_cloud.html.erb
<div class="col-lg-4">
           <h3>Search Tags</h3>
           <div>
            <% tag_cloud(Event.tag_counts, %w{css1 css2 css3 css4}) do |tag, css_class| %>
              <%= link_to tag.name, tag_path(tag.name), class: css_class %>
            <% end %>
          </div>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>
<%= link_to 'Create an Event', new_event_path,
         :class=>"btn btn-default btn-primary" %>
<% if Tag.all.length > 0 %>

<% end %>
<table class=" table table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Location</th>
      <th>Agenda</th>
      <th>Address</th>
      <th>Organizer</th>
      <th>All Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.start_date.strftime("%d-%m-%Y %H:%M %p") if event.start_date%></td>
        <td><%= event.end_date.strftime("%d-%m-%Y %H:%M %p") if event.end_date%></td>
        <td><%= event.location %></td>
        <td><%= event.agenda %></td>
        <td><%= event.address %></td>
        <td><%= User.find(event.organizer_id).email %></td>
        <td><% event.all_tags.gsub(' ', '').split(',').map do |t| %>
          <%= (link_to t, tag_path(t))%>
          <% end %> </td>

        <td><%= link_to 'Show', event %></td>
        <%if current_user == event.organizer %>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/my_events.html.erb
<p id="notice"><%= notice %></p>

<h1>My Events</h1>
<%= link_to 'Create an Event', new_event_path,
         :class=>"btn btn-default btn-primary" %>

<%= render 'events/tag_cloud' %>

<table class=" table table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Location</th>
      <th>Agenda</th>
      <th>Address</th>
      <th>Organizer</th>
      <th>All Tags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.title %></td>
        <td><%= event.start_date.strftime('%d/%m/%Y')%></td>
        <td><%= event.end_date.strftime('%d/%m/%Y')%></td>
        <td><%= event.location %></td>
        <td><%= event.agenda %></td>
        <td><%= event.address %></td>
        <td><%= event.organizer_id %></td>
        <td><% event.all_tags.split(',').map do |t| %>
          <%= (link_to t + ", ", tag_path(t))%>
          <% end %> </td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-3">
<% if user_signed_in? && @event.organizer_id == current_user.id %>
<label> <%= @pending_requests.length %> Join Requests</label>

  <% if @pending_requests.present? %>
    <% @pending_requests.each do |p| %>
    <li><%= image_tag avatar_url(p.user), style: 'height: 30px; width: 30px;', class: 'thumbnail' %>
    <%= p.user.email %>
    <%= link_to 'Accept', accept_request_path(:event_id => @event.id, :attendance_id => p.id), :class => 'btn btn-success btn-small' %>
    <%= link_to 'Reject', reject_request_path(:event_id => @event.id, :attendance_id => p.id), :class => "btn btn-danger btn-small"%></li>
    <% end %>
  <% else %>
    <p>No Pending Requests for this event</p>
  <% end %>
<% end %>
</div>

<div class="col-md-6">

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date.strftime('%d/%m/%Y') %>
</p>

<p>
  <strong>End date:</strong>
  <%= @event.end_date.strftime('%d/%m/%Y') %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Agenda:</strong>
  <%= @event.agenda %>
</p>

<p>
  <strong>Address:</strong>
  <%= @event.address %>
</p>

<label>Organized By:</label><br/>
         
           <%= image_tag avatar_url(@event.organizer), style: 'height: 30px; width: 30px;', class: 'thumbnail'  %>
           <%= @event.organizer.email %>
         
<br/>

<p>
  <strong>All Tags:</strong>
  <%= @event.all_tags %>
</p>

<%= link_to 'Join', join_path(:event_id =>
         @event.id), class: 'btn btn-info' %> 
<% if current_user == @event.organizer %>
<%= link_to 'Edit', edit_event_path(@event), class: 'btn btn-primary' %> |
<% end %>
<%= link_to 'Back', events_path, class: 'btn btn-danger' %>
</div>


<div class="col-md-3">


<% if (@attendees.length > 1)%>
  
<label><%= @attendees.length %> Attendees</label>
<% elsif @attendees.length == 1 %>

<label><%= @attendees.length %> Attendant</label>
<% else %>
<label>No Attendants For This Event</label>
<% end %>

<% if current_user == @event.organizer %>
<ul>
  
       <% @attendees.each do |a|%>
         <li><%= image_tag avatar_url(a.user), style: 'height: 30px; width: 30px;', class: 'thumbnail' %>
         <%= a.user.email %></li>
       <%end%>
     
     </ul>
     <% end %>
</div></div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top col-lg-12 ">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display
    -->
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" data-target="#main-nav" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Eventually", root_path, class: "navbar-brand", style: "color: blue;" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling
    -->
    <div class="collapse navbar-collapse" id="main-nav">
      

     
        
      <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
       
        <li><button style="margin: 10px;" class="btn btn-danger" type="submit"><i class="fa fa-search"></i><%= link_to "My Events", my_events_path, style: "color:white;"%></button> </li>
        <li class="dropdown">
<a style="color: blue;" class="dropdown-toggle" role="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Signed in as <%= current_user.email %><span class="caret"></span></a>
            



          





          
          <ul class="dropdown-menu">
            
          
            <li><%= link_to "Edit Profile", edit_user_registration_path  %></li>
            
            <li><%= link_to "Log out.", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
          
        <li><%= link_to "Log out.", destroy_user_session_path, method: :delete, style:"color: white;" %></li>
        
      </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          
            <li><%= link_to "Sign Up", new_user_registration_path, style:"color: blue;"  %>
          </li>
          <li>
            <%= link_to "Log in", new_user_session_path, style:"color: blue;"  %>
          </li>
        </ul>
      <% end %>
    
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventually</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>